# we don't build in Travis, we build in Docker, so no language support is needed 
language: generic

services:
  - docker

script:
  - docker build --rm -f "Dockerfile" -t exercism-cpp-hello-world:test-1 .
